version: '3.8'

services:
  resume-generator:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    volumes:
      - ./temp:/app/temp
    restart: unless-stopped
